name: kampusgratis
description: A Very Good Project created by Very Good CLI.
version: 2.0.0-beta+39
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  administration_repository:
    path: packages/administration_repository
  authentication_repository:
    path: packages/authentication_repository
  banner_repository:
    path: packages/banner_repository
  bloc: ^8.1.2
  bootcamp_repository:
    path: packages/bootcamp_repository
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  dynamic_color: ^1.6.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_cached_pdfview: ^0.4.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  formz: ^0.6.1
  freezed_annotation: ^2.4.1
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.3
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  intl: ^0.18.0
  json_annotation: ^4.8.1
  kg_client:
    path: packages/kg_client
  my_study_repository:
    path: packages/my_study_repository
  package_info_plus: ^5.0.1
  path_provider: ^2.1.2
  phosphor_flutter: ^2.0.1
  pinput: ^3.0.1
  stream_listener:
    path: packages/stream_listener
  transparent_image: ^2.0.1
  url_launcher: ^6.2.4
  user_repository:
    path: packages/user_repository
  youtube_player_iframe: ^5.0.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  change_app_package_name: ^1.1.0
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  go_router_builder: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter_gen:
  integrations:
    flutter_svg: true

  fonts:
    enabled: false
    
  colors:
    enabled: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
  