name: kg_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  fresh_dio: ^0.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  ua_client_hints: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
